# Generated by Django 3.0.5 on 2023-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_itemcart_itemorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
